version: '3.1'
services:
  db:
    image: mongo:4.4.27-focal
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
